FROM tomcat:9-jre8-alpine
RUN rm -r $CATALINA_HOME/webapps/ROOT
COPY rideout/rideout-api.war $CATALINA_HOME/webapps/ROOT.war
EXPOSE 8080

HEALTHCHECK --interval=1m --timeout=3s CMD wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1
